version: 2
dist: build
before:
  hooks:
    - npm install
    - npm run package
    - npx vsce package --out vor-stream-{{ .Version }}.vsix

builds:
  - builder: bun
    skip: true

archives:
  - id: default
    formats: ["zip"]
    name_template: "vor-stream-{{ .Version }}"
    files:
      - "README.md"
      - "LICENSE"
      - "package.json"
      - "vor-stream-{{ .Version }}.vsix"
    meta: true

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
      - Merge pull request
      - Merge branch

checksum:
  name_template: "checksums.txt"

snapshot:
  version_template: "{{ incpatch .Version }}-next"
