repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: end-of-file-fixer
        exclude: "src/_js_parser/"
      - id: trailing-whitespace
        exclude: "src/_js_parser/"

  - repo: local
    hooks:
      - id: prettier
        name: prettier
        language: node
        entry: node_modules/.bin/prettier
        args: ["--write"]
        types_or: [javascript, ts, json, markdown, yaml]
        exclude: "src/_js_parser/"

  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v3.4.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
        args:
          [
            feat,
            fix,
            docs,
            style,
            refactor,
            test,
            build,
            ci,
            chore,
            revert,
            perf,
          ]
